title: <img src="./logo.svg" alt="LoAT">
email: florian.frohn@cs.rwth-aachen.de
description: >- # this means to ignore newlines until "baseurl:"
  We present Accelerated Bounded Model Checking (ABMC).
  It uses acceleration to enable BMC to find deep counterexamples with small bounds.
  Moreover, by using so-called blocking clauses, ABMC can also prove safety of examples that are challenging for state-of-the-art techniques.
github_username:  ffrohn
theme: jekyll-theme-cayman
github:
  is_project_page: false